# Generated by Django 4.0.4 on 2022-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('USMC', 'U.S. Marine Corps'), ('USA', 'U.S. Army'), ('USN', 'U.S. Navy'), ('USAF', 'U.S. Air Force'), ('USCG', 'U.S. Army'), ('Other', 'Other Service')], max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='current_status',
            field=models.CharField(choices=[('ACT', 'Active'), ('RES', 'Reserve'), ('VET', 'Veteran')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('E', 'Enlisted'), ('O', 'Officer'), ('W', 'Warrant Officer')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
