# Generated by Django 4.0.4 on 2022-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_branch_user_current_status_user_grade_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('USMC', 'U.S. Marine Corps'), ('USA', 'U.S. Army'), ('USN', 'U.S. Navy'), ('USAF', 'U.S. Air Force'), ('USCG', 'U.S. Coast Guard'), ('Other', 'Other Service')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
