# Generated by Django 4.0.4 on 2022-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=6048, upload_to='documents/macbook_dad/coding/images'),
            preserve_default=False,
        ),
    ]
