# Generated by Django 4.0.4 on 2022-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='documents/macbook_doc/coding/images/default.jpeg', upload_to='documents/macbook_doc/coding/images'),
        ),
    ]
