# Generated by Django 4.0.4 on 2022-05-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_branch_alter_user_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
