# Generated by Django 4.0.4 on 2022-05-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
