# Generated by Django 4.0.4 on 2022-05-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('USMC', 'U.S. Marine Corps'), ('USA', 'U.S. Army'), ('USN', 'U.S. Navy'), ('USAF', 'U.S. Air Force'), ('USCG', 'U.S. Coast Guard'), ('Other', 'Other Service')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_status',
            field=models.CharField(choices=[('ACT', 'Active'), ('RES', 'Reserve'), ('VET', 'Veteran')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('E', 'Enlisted'), ('O', 'Officer'), ('W', 'Warrant Officer')], max_length=2),
        ),
    ]
