# Generated by Django 4.0.4 on 2022-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_branch_alter_user_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
