# Generated by Django 4.0.4 on 2022-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images/'),
        ),
    ]
